Silownia/Controllers/BasketController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Silownia.DAL;
using Silownia.Models;
using PagedList;
using System.IO;
using System.Diagnostics;

namespace Silownia.Controllers
{
    
    [Authorize]
    public class BasketController : Controller
    {
        private GymContext db = new GymContext();
        public static List<Pass> listInBasket = new List<Pass>();

        // GET: Basket strona koszyka
        public ViewResult Index(int? id)
        {
            if (id == null || id == 0)
            {
                return View(listInBasket);
            }
            Pass pass = db.Pass.Find(id);

            foreach(var item in listInBasket)
            {
                if(item.ID == pass.ID)
                {
                    return View(listInBasket);
                }
            }
            listInBasket.Add(pass);
            return View(listInBasket);
        }

        //Get: Delete {id} usuwanie z koszyka
        public ViewResult Delete(int? id)
        {
            foreach (var item in listInBasket)
            {
                if(item.ID == id)
                {
                    listInBasket.Remove(item);
                    break;
                }
            }
            
            
           return View("Index", listInBasket);
        }

        //Get: DoOrder składanie zamówień
        public ViewResult DoOrder()
        {
            if (listInBasket.Count == 0)
            {
                return View("Index", listInBasket);
            }
            float priceAll = 0;
            foreach(var item in listInBasket)
            {
                priceAll = priceAll + item.Price;
            }

            //wyszukiwanie zalogowanego użytkownika

            var prof = db.Profiles.Select(n => n).Where(n => n.UserName == User.Identity.Name);

            Profile profile = null;

            foreach (var item in prof)
            {
                profile = item;
            }

            //wyszukanie odpowiedniego statusu

            var stat = db.Status.Select(n => n).Where(n => n.Name == "Oczekuje");

            Status status = null;

            foreach (var item in stat)
            {
                status = item;
            }

            //tworzenie zamowienia
            Order order = new Order { Price = priceAll, Data_Order = DateTime.Now, Profile = profile, Status = status };

            db.Order.Add(order);
            db.SaveChanges();

            //tworzenie informacji jakie produktu należą do zamówienia
            Pass pass = null;
            foreach (var item in listInBasket)
            {
                var passQ = db.Pass.Select(n => n).Where(n => n.ID == item.ID);

                foreach (var itemQ in passQ)
                {
                    pass = itemQ;
                }

                Order_Pass order_pass = new Order_Pass {Pass = pass, Order = order};
                db.Order_Pass.Add(order_pass);
                db.SaveChanges();
            }

            listInBasket.Clear();

            var apikey = "YiaYlpjdIK64lvGaKQMPW52EyK27y4vVuGEg5AOI";

            var address = "https://api.smsapi.pl/sms.do?access_token=";

            //var id1 = zamowienia.Profile_ID1;

            var numer = "48" + profile.NumberPhone;
            //var email = profil.UserName;
            var message = "System przyjal twoje zamowienie, dziekujemy!";

            var url = address + apikey + "&to=" + numer + "&message=" + message + "&sender=" + "&fast=1&format=json";

            HttpWebRequest req = (HttpWebRequest)WebRequest.Create(url);
            HttpWebResponse resp = (HttpWebResponse)req.GetResponse();
            StreamReader sr = new StreamReader(resp.GetResponseStream());
            string results = sr.ReadToEnd();
            Debug.WriteLine(results);
            sr.Close();

            return View("Index", listInBasket);
        }
    }
}

Silownia/Controllers/PassesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Silownia.DAL;
using Silownia.Models;
using PagedList;

namespace Silownia.Controllers
{
    [Authorize]
    public class PassesController : Controller
    {
        private GymContext db = new GymContext();
        
        // GET: Passes
        public ViewResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name" : "";
            ViewBag.TimeSortParm = sortOrder == "Time" ? "time_desc" : "Time"; ;
            ViewBag.PriceSortParm = sortOrder == "Price" ? "price_desc" : "Price"; ;
            var pass = from s in db.Pass select s;

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                pass = pass.Where(s => s.Name.Contains(searchString));
                    
            }

            switch (sortOrder)
            {
                case "Name":
                    pass = pass.OrderByDescending(s => s.Name);
                    break;
                case "Price":
                    pass = pass.OrderBy(s => s.Price);
                    break;
                case "price_desc":
                    pass = pass.OrderByDescending(s => s.Price);
                    break;
                case "Time":
                    pass = pass.OrderBy(s => s.Time);
                    break;
                case "time_desc":
                    pass = pass.OrderByDescending(s => s.Time);
                    break;
                default:
                    pass = pass.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(pass.ToPagedList(pageNumber, pageSize));
        }

        // GET: Passes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pass pass = db.Pass.Find(id);
            if (pass == null)
            {
                return HttpNotFound();
            }
            return View(pass);
        }

        // GET: Passes/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Passes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ID,Name,Time,Price,Photo")] Pass pass)
        {

            HttpPostedFileBase file = Request.Files["plikZObrazkiem"];
            if(file != null && file.ContentLength > 0)
            {
                pass.Photo = file.FileName;
                file.SaveAs(HttpContext.Server.MapPath("~/Photo/") + pass.Photo);
            }

            if (ModelState.IsValid)
            {
                db.Pass.Add(pass);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(pass);
        }

        // GET: Passes/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pass pass = db.Pass.Find(id);
            string zdjecie = pass.Photo;
            if (pass == null)
            {
                return HttpNotFound();
            }
            return View(pass);
        }

        // POST: Passes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "ID,Name,Time,Price,Photo")] Pass pass)
        {
           
            HttpPostedFileBase file = Request.Files["plikZObrazkiem"];
            
            if (file != null && file.ContentLength > 0)
            {
                pass.Photo = file.FileName;
                file.SaveAs(HttpContext.Server.MapPath("~/Photo/") + pass.Photo);
            }

            if (ModelState.IsValid)
            {
                db.Entry(pass).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pass);
        }

        // GET: Passes/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pass pass = db.Pass.Find(id);
            if (pass == null)
            {
                return HttpNotFound();
            }
            return View(pass);
        }

        // POST: Passes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Pass pass = db.Pass.Find(id);
            db.Pass.Remove(pass);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Silownia/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://code.jquery.com/jquery-1.6.4.js"
            integrity="sha256-VJZPi1gK15WpYvsnBmcV0yga4a0Toov4rt1diFnrrjc="
            crossorigin="anonymous"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Siłownia", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- malpaif (Request.IsAuthenticated) !-->
                    <li>@Html.ActionLink("Zajęcia", "Index", "Activites")</li>
                    @if (Context.User.IsInRole("User") || Context.User.IsInRole("Coach"))
                    {
                        <li>@Html.ActionLink("Moje zajęcia", "MyActivites", "Activites", null, null)</li>
                    }
                    <li>@Html.ActionLink("Karnety", "Index", "Passes")</li> 
                   
                    @if (Context.User.IsInRole("User")) 
                    {
                       <li>@Html.ActionLink("Koszyk", "Index", "Basket", new { id = 0}, null) </li>
                    }
                    @if (Context.User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Panel administratora", "Index", "FulFillOrder")</li>
                    }
                    @if (Context.User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("Moje zamówienia", "UserOrder", "FulFillOrder")</li>
                    }
                    @if (Context.User.IsInRole("User"))
                    {
                        <li>@Html.ActionLink("Dieta", "Index", "Diet")</li>
                    }@if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Chat", "Chat", "Home")</li>
                    }
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>